Repository falcosecurity/libs, pull requests merged in 2022-09, with the labels that each got.

#575 fix(libsinsp): keep the copy of cgroups alive across the write
  userspace/libsinsp/threadinfo.cpp
  userspace/libsinsp/threadinfo.h
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#573 new(ci): run tests with AddressSanitizer on x86_64
  .github/workflows/ci.yml
Labels: kind/feature, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/tests

#547 update(userspace/plugin): bump plugin API version to 2.0.0
  userspace/plugin/plugin_api.h
Labels: kind/documentation, kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/L

#586 update(readme): add a beautiful archs badge that links to proper section in readme
  README.md
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup

#589 update(userspace/libsinsp): k8s filterchecks documentation desc
  userspace/libsinsp/filterchecks.cpp
Labels: kind/documentation, kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libsinsp

#590 update(OWNERS): add Hendrik Brueckner (hbrueckner) as reviewer
  OWNERS
Labels: kind/documentation, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/proposals

#572 new(libsinsp/test): Test open/openat/creat NULL filenames and enter/exit string disagreements
  userspace/libsinsp/test/sinsp.ut.cpp
Labels: kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, area/libsinsp, area/tests, size/L

#598 chore(userspace/libsinsp): improve `get_event_type` util method in sinsp-example
  userspace/libsinsp/examples/util.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, kind/cleanup, size/XL

#597 fix(driver/kmod): fixed tracepoint detach to avoid dmesg errors.
  driver/main.c
Labels: kind/bug, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/driver-kmod

#599 chore(userspace/libsinsp): move new `enforce_X_ppm_sc` near to `enforce_sinsp_state_ppm_sc`
  userspace/libsinsp/sinsp.h
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M, kind/cleanup, area/libsinsp

#600 chore(driver): allow modern probe to compute API/SCHEMA versions
  cmake/modules/compute_versions.cmake
  driver/CMakeLists.txt
  driver/modern_bpf/CMakeLists.txt
Labels: kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, size/M, area/build

#602 fix(userspace/libsinsp): use self instead of inspector's usergroup_manager
  userspace/libsinsp/user.cpp
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libsinsp

#607 fix(bpf): fallback for unsupported prog_names
  userspace/libscap/engine/bpf/scap_bpf.c
Labels: kind/bug, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/driver-bpf

#583 add filter execution statistics to be analyzed by the clients
  userspace/libsinsp/filter.cpp
  userspace/libsinsp/gen_filter.cpp
  userspace/libsinsp/gen_filter.h
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M

#613 fix(CI): remove an old reference
  userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/driver-modern-bpf

#616 update(build): use -Og when debugging
  cmake/modules/CompilerFlags.cmake
Labels: kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/build

#608 chore(libscap): Check handle for NULL in scap API
  userspace/libscap/scap.c
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/libscap

#619 build(.github): enable CI workflow on all branches
  .github/workflows/ci.yml
Labels: kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/CI

#603 new(test): add "Coverage" build type to generate test coverage info
  cmake/modules/CompilerFlags.cmake
  userspace/libscap/test/CMakeLists.txt
  userspace/libsinsp/test/CMakeLists.txt
Labels: kind/feature, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/libscap, area/libsinsp, area/tests

#623 new(modern_bpf): change `sys_enter` and `sys_exit` prog names
  driver/modern_bpf/programs/attached/dispatchers/syscall_enter.bpf.c
  driver/modern_bpf/programs/attached/dispatchers/syscall_exit.bpf.c
  userspace/libpman/src/programs.c
Labels: kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, size/M, area/driver-modern-bpf

#624 new(scap-open): add the `simple_set` mode
  userspace/libscap/examples/01-open/scap_open.c
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/L

#639 Initialize evtnum in sinsp_evt::init methods
  userspace/libsinsp/event.h
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#638 fix(libsinsp): refresh user / group when detecting a container
  userspace/libsinsp/parsers.cpp
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/M

#641 fix(engine/gvisor): allow empty (default) root path
  userspace/libsinsp/sinsp.cpp
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/libscap, area/libscap-engine-gvisor
