Repository falcosecurity/libs, pull requests merged in 2023-05, with the labels that each got.

#1072 cleanup(tests): do not assert_throw when we check if a field exists
  userspace/libsinsp/test/events_net.ut.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M, kind/cleanup, area/tests

#1073 fix(userspace/libsinsp): support EOF in sinsp-example
  userspace/libsinsp/examples/test.cpp
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libsinsp

#1074 fix(userspace/libsinsp): properly format double numbers as json
  userspace/libsinsp/filter.cpp
  userspace/libsinsp/filterchecks.cpp
Labels: kind/bug, release-note, dco-signoff: yes, size/S, lgtm, approved, area/libsinsp

#1075 update(readme): modern eBPF probe has feature parity and is out of wip.
  README.md
Labels: kind/documentation, dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#1080 tests(userspace): fix test mode
  userspace/libscap/scap.c
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/tests

#1084 fix(ci): fix s390x CI and remove a duplicated job
  .github/workflows/ci.yml
  driver/modern_bpf/CMakeLists.txt
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/M, kind/cleanup, area/build, area/CI

#1082 update(ci): use BUILD_WARNINGS_AS_ERRORS
  .github/workflows/ci.yml
Labels: kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/CI

#1085 chore(docs): updated README properly stating that any new kernel release might break drivers build
  README.md
Labels: kind/documentation, dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#1095 docs(userspace/libsinsp): more detailed docs about proc filterchecks
  userspace/libsinsp/filterchecks.cpp
Labels: dco-signoff: yes, size/S, lgtm, approved

#1103 fix(userspace/libsinsp): don't unset async evt handler if inspector was not open
  userspace/libsinsp/events/sinsp_events.cpp
  userspace/libsinsp/filter/ppm_codes.cpp
  userspace/libsinsp/filterchecks.cpp
  userspace/libsinsp/sinsp.cpp
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/libsinsp

#1105 fix(userspace/plugin): make plugin loader less strict when checking caps
  userspace/plugin/plugin_loader.c
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/libsinsp

#1108 update(userspace/libsinsp): support lists of new field types
  userspace/libsinsp/filter.cpp
Labels: kind/bug, kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/M, area/libsinsp

#1112 update(cmake): update c-ares to 1.19.1
  cmake/modules/cares.cmake
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/build, area/libsinsp

#1113 fix(test,userspace): fixed strncat usage.
  test/drivers/start_tests.cpp
  userspace/libpman/src/stats.c
  userspace/libscap/engine/bpf/scap_bpf.c
  userspace/plugin/plugin_loader.c
Labels: kind/bug, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/libsinsp, area/tests, area/libscap-engine-bpf, area/libscap-engine-modern-bpf

#1116 fix(libsinsp): return on error in update_container_with_size
  userspace/libsinsp/container.cpp
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/libsinsp

#1120 chore(userspace/libsinsp): make get_field_names a property of generic formatters
  userspace/libsinsp/eventformatter.h
  userspace/libsinsp/gen_filter.h
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS, kind/cleanup, area/libsinsp

#1121 fix(libpman): do not close cnt map in scap stats v2 in absence of error
  userspace/libpman/src/stats.c
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libpman

#1110 fix(driver): fixed 6.4 kernel build
  driver/main.c
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/driver-kmod

#1124 tests: add some engine tests on scap stats
  test/libscap/test_suites/engines/bpf/bpf.cpp
  test/libscap/test_suites/engines/kmod/kmod.cpp
  test/libscap/test_suites/engines/modern_bpf/modern_bpf.cpp
Labels: kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, area/tests, size/L
