Repository falcosecurity/libs, pull requests merged in 2024-10, with the labels that each got.

#2090 chore(ci): show diff on failed format
  .github/workflows/format.yml
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/CI

#2091 new(libsinsp): print LIST() in markdown format for list fields
  userspace/libsinsp/filter.cpp
  userspace/libsinsp/filter.h
Labels: kind/feature, release-note, dco-signoff: yes, size/S, lgtm, approved, area/libsinsp

#2095 fix(driver/bpf): fix sys_poll_x verifier bug on fedora 40
  driver/bpf/fillers.h
Labels: release-note, dco-signoff: yes, lgtm, approved, size/XS

#2093 cleanup: remove some commits from the blame
  .git-blame-ignore-revs
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup

#2071 fix(tests): flaky thread pool tests
  userspace/libsinsp/test/plugins.ut.cpp
  userspace/libsinsp/test/thread_pool.ut.cpp
Labels: kind/failing-test, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/tests

#2108 fix(ci): fix kernel testing action by using proper tag name.
  .github/workflows/reusable_kernel_tests.yaml
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/CI

#2109 fix(ci): fix build-scap-open-w-extern-bpf-skeleton job
  .github/workflows/drivers_ci.yml
  .github/workflows/pages.yml
  .github/workflows/release-body.yml
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M, kind/cleanup, area/CI

#2112 fix(userspace/libscap): scap-gvisor does need to depend upon jsoncpp.
  userspace/libscap/engine/gvisor/CMakeLists.txt
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libscap-engine-gvisor

#2113 fix(userspace/libsinsp): disable HTTP proxy for CRI connection
  userspace/libsinsp/cri.hpp
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libsinsp

#2115 fix(userspace/libsinsp): stringop-overflow on libvirt_lxc
  userspace/libsinsp/container_engine/libvirt_lxc.cpp
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#2119 fix(modern): check `cred` field is not NULL before the access
  driver/modern_bpf/helpers/extract/extract_from_kernel.h
Labels: kind/bug, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/driver-modern-bpf

#2120 fix(ci): fixed latest-kernel CI usage of steps/jobs outputs.
  .github/workflows/latest-kernel.yml
Labels: kind/bug, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/CI

#2123 fix(ci): use `process.exit();` to leave node script in github/action-script
  .github/workflows/create-comment-kernel-testing.yml
  .github/workflows/create-comment-perf.yml
Labels: kind/bug, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/CI

#2125 fix(ci): create-comment workflows array length check.
  .github/workflows/create-comment-kernel-testing.yml
  .github/workflows/create-comment-perf.yml
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/CI

#2132 fix(libsinsp): use correct regex for hex numbers
  userspace/libsinsp/filter/parser.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup

#2135 fix(libsinsp): invalid field_info check
  userspace/libsinsp/state/dynamic_struct.h
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#2133 fix(libsinsp): expose main thread fd table
  userspace/libsinsp/threadinfo.cpp
  userspace/libsinsp/threadinfo.h
Labels: kind/bug, kind/feature, release-note, dco-signoff: yes, size/S, lgtm, approved, area/libsinsp

#2130 fix(userspace/libsinsp): multiple fixes related to rawargs.
  userspace/libsinsp/sinsp_filtercheck.cpp
  userspace/libsinsp/sinsp_filtercheck_event.cpp
  userspace/libsinsp/sinsp_filtercheck_event.h
  userspace/libsinsp/test/filterchecks/evt.cpp
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/M, area/libsinsp

#2138 cleanup: improve perf `populate_cmdline`
  userspace/libsinsp/threadinfo.cpp
  userspace/libsinsp/threadinfo.h
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/libsinsp
