Repository falcosecurity/libs, pull requests merged in 2024-09, with the labels that each got.

#2011 fix(driver): fixed build against linux 6.11.
  driver/bpf/fillers.h
  driver/modern_bpf/definitions/struct_flavors.h
  driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c
  driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c
  driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, area/driver-bpf, size/L, area/driver-modern-bpf

#2041 cleanup(ci): don't run drivers CI job that use secrets on forks.
  .github/workflows/drivers_ci.yml
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/CI

#2042 fix(modern): prevent CO-RE relocations when CONFIG_QUOTACTL is not defined
  driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/quotactl.bpf.c
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/L, area/driver-modern-bpf

#2036 chore(userspace/libsinsp): only link libanl if present.
  userspace/libsinsp/CMakeLists.txt
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/libsinsp

#2043 chore(cmake): honor CMAKE_BUILD_TYPE while building bundled grpc and protobuf
  cmake/modules/grpc.cmake
  cmake/modules/protobuf.cmake
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/build

#2046 fix(schema): fix FUTEX_E flags parameter
  driver/SCHEMA_VERSION
  driver/event_table.c
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#2048 ci(semgrep): update semgrep docker image
  .github/workflows/semgrep_checks.yml
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/CI

#2050 fix(sinsp): plugin capture listen capability exception
  userspace/libsinsp/sinsp.cpp
Labels: kind/bug, release-note, dco-signoff: yes, size/S, lgtm, approved, area/libsinsp

#2054 chore: ignore the commit used for formatting
  .git-blame-ignore-revs
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup

#2062 fix(ci): fix some warnings as error
  test/drivers/event_class/network_utils.h
  test/drivers/helpers/proc_parsing.h
  test/drivers/test_suites/generic_tracepoints_suite/sched_process_exec.cpp
  test/drivers/test_suites/generic_tracepoints_suite/sched_process_fork.cpp
  test/drivers/test_suites/syscall_enter_suite/connect_e.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M

#2060 fix(ci): avoid running drivers CI jobs that need secrets in PR coming from forks
  .github/workflows/drivers_ci.yml
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/CI

#2058 chore(libs): fix -Werror=unused-variable
  driver/configure/CLASS_CREATE_1/test.c
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/build

#2065 chore(sinsp): rename `thread_pool` to `sinsp_thread_pool` to avoid symbol conflicts
  userspace/libsinsp/CMakeLists.txt
  userspace/libsinsp/plugin.cpp
  userspace/libsinsp/plugin.h
  userspace/libsinsp/sinsp.cpp
  userspace/libsinsp/sinsp.h
  userspace/libsinsp/sinsp_thread_pool.h
  userspace/libsinsp/sinsp_thread_pool_bs.cpp
  userspace/libsinsp/sinsp_thread_pool_bs.h
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M

#2066 fix(test/drivers): fixed s390x `Werror` related failures for drivers tests
  test/drivers/test_suites/syscall_enter_suite/socketcall_e.cpp
  test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp
  test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/M, area/tests

#2055 ci: pin dependencies
  .github/workflows/format.yml
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#2067 fix(libscap): use the correct memory barrier for ARM64
  userspace/libpman/src/ringbuffer_definitions.h
  userspace/libscap/engine/bpf/scap_bpf.h
  userspace/libscap/linux/barrier.h
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/L, area/libscap-engine-bpf, area/libscap-engine-kmod, area/libpman

#2070 chore(ci): bumped perf unit tests threshold to 5% (relative) slowdown.
  .github/workflows/perf.yml
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/CI

#2073 chore(test/libsinsp_e2e,ci): port libsinsp_e2e tests to use python3.
  .github/workflows/e2e_ci.yml
  test/libsinsp_e2e/resources/unix_client_server.py
  test/libsinsp_e2e/unix_client_server.cpp
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/tests, area/CI

#2034 update(cmake): updated c-ares to latest 1.33.1 version.
  cmake/modules/cares.cmake
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M, kind/cleanup, area/build

#2072 chore: downgrade flushing log messages to debug
  userspace/libsinsp/container.cpp
  userspace/libsinsp/sinsp.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/libsinsp

#2037 cleanup(userspace/libscap): avoid the usage of non-portable (glibc specific) `__gnu_cxx::stdio_filebuf`
  userspace/libscap/engine/gvisor/runsc.cpp
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/libscap-engine-gvisor

#2080 fix(libsinsp-e2e-tests): stop capture upon stop_capture()
  test/libsinsp_e2e/event_capture.cpp
Labels: kind/bug, dco-signoff: yes, release-note-none, size/S, lgtm, approved, area/tests

#2081 fix(userspace/libsinsp): avoid dereferencing a possible nullptr in parsers
  userspace/libsinsp/parsers.cpp
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/libsinsp

#2082 sync: release 0.18.1
  userspace/libsinsp/parsers.cpp
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libsinsp

#2083 fix(benchmark): avoid compiler optimizations in benchmarks loops.
  benchmark/libsinsp/utils.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M, kind/cleanup, area/tests

#2084 fix(schema): make OPENAT2_E DIRFD_PARAM point to the right param
  driver/SCHEMA_VERSION
  driver/event_table.c
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/API-version

#2087 chore(driver/bpf): properly include sched.h in types.h since it uses `TASK_COMM_LEN`
  driver/bpf/probe.c
  driver/bpf/types.h
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/driver-bpf

#2088 fix(userspace/libsinsp): avoid possible UB when calling `back` or `front` without checking string emptiness
  userspace/libsinsp/parsers.cpp
  userspace/libsinsp/sinsp_filtercheck_fdlist.cpp
  userspace/libsinsp/sinsp_filtercheck_fspath.cpp
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libsinsp
