Repository falcosecurity/libs, pull requests merged in 2024-11, with the labels that each got.

#2143 fix(driver): include jiffies.h to prevent warning about missing prototype
  driver/ppm_cputime.c
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/driver-kmod

#2147 new(userspace/libsinsp): expose `get_owner_last_error` in plugin's capture listening capability
  userspace/libsinsp/plugin.cpp
  userspace/libsinsp/sinsp.cpp
  userspace/plugin/plugin_api.h
Labels: release-note, dco-signoff: yes, size/S, lgtm, approved, kind/cleanup, area/libsinsp

#2140 cleanup(tests): add some exceptions in sinsp test framework
  userspace/libscap/scap_event.c
  userspace/libsinsp/test/sinsp_with_test_input.cpp
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/tests

#2146 chore: cleanup CMake dependencies
  cmake/modules/libelf.cmake
  userspace/libsinsp/test/CMakeLists.txt
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/build

#2136 chore(e2e): fix e2e build without bundled deps
  test/libsinsp_e2e/CMakeLists.txt
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/build

#2154 ci: disable a flaky test
  userspace/libsinsp/test/async_key_value_source.ut.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/CI

#2164 fix(libsinsp): max proc lookup number logging
  userspace/libsinsp/threadinfo.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M

#2166 chore(libsinsp): reduce max proc lookup number log severity
  userspace/libsinsp/threadinfo.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/libsinsp

#2156 cleanup(sinsp): remove some duplicated code
  userspace/libsinsp/sinsp_filtercheck_event.cpp
  userspace/libsinsp/test/filterchecks/evt.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M, kind/cleanup, area/libsinsp

#2170 update(libsinsp): introduce a description to sinsp_filter_transformer
  userspace/libsinsp/sinsp_filter_transformer.h
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M

#2160 cleanup(sinsp): handle path too long in a better way
  test/libsinsp_e2e/sys_call_test.cpp
  userspace/libsinsp/test/events_file.ut.cpp
  userspace/libsinsp/test/sinsp_utils.ut.cpp
  userspace/libsinsp/utils.cpp
  userspace/libsinsp/utils.h
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/libsinsp
