Repository falcosecurity/libs, pull requests merged in 2024-06, with the labels that each got.

#1887 fix: some compiler warnings (func def. w/o decl.)
  driver/main.c
  driver/ppm_fillers.c
  userspace/libscap/engine/gvisor/gvisor.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, kind/cleanup, area/build, size/L

#1895 fix(userspace/libsinsp): Include cri.hpp in container.cpp
  userspace/libsinsp/container.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/libsinsp

#1897 chore: update test/vm setup
  test/README.md
  test/vm/CMakeLists.txt
  test/vm/containers/debianbuster.Dockerfile
  test/vm/containers/ubuntu2404.Dockerfile
  test/vm/kernels.jsonl
  test/vm/scripts/compile_drivers.sh
  test/vm/scripts/main.go
  test/vm/scripts/vm_compile.sh
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/M, kind/cleanup, area/tests

#1902 chore(cmake): workaround CI issue for windows.
  cmake/modules/CompilerFlags.cmake
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/CI

#1896 fix(driver/bpf): fixed a couple of verifier issues.
  driver/bpf/fillers.h
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, area/driver-bpf, size/XL

#1912 new(tests): add tests for contains/icontains
  userspace/libsinsp/test/CMakeLists.txt
  userspace/libsinsp/test/filter_op_contains.ut.cpp
Labels: kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, size/M, area/tests

#1911 cleanup(tests): move filter compilation functions to sinsp_with_test_input
  userspace/libsinsp/test/events_fspath.ut.cpp
  userspace/libsinsp/test/filter_compiler.h
  userspace/libsinsp/test/filter_compiler.ut.cpp
  userspace/libsinsp/test/filter_op_bcontains.ut.cpp
  userspace/libsinsp/test/filter_op_pmatch.ut.cpp
  userspace/libsinsp/test/plugins.ut.cpp
  userspace/libsinsp/test/sinsp_with_test_input.cpp
  userspace/libsinsp/test/sinsp_with_test_input.h
Labels: dco-signoff: yes, release-note-none, lgtm, approved, kind/cleanup, area/tests, size/XL

#1914 new(test): add test for gvisor config generator
  userspace/libsinsp/test/CMakeLists.txt
  userspace/libsinsp/test/gvisor_config.ut.cpp
Labels: kind/feature, dco-signoff: yes, release-note-none, lgtm, approved, size/M, area/tests

#1917 fix(libsinsp): resize the param storage in case of a long path
  userspace/libsinsp/event.cpp
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libsinsp

#1915 cleanup(libsinsp): remove unreachable code in utils.cpp
  userspace/libsinsp/utils.cpp
  userspace/libsinsp/utils.h
Labels: dco-signoff: yes, release-note-none, lgtm, approved, kind/cleanup, area/libsinsp, size/L

#1922 fix(libsinsp): add missing #include <map>
  userspace/libsinsp/prefix_search.h
Labels: kind/bug, release-note, dco-signoff: yes, lgtm, approved, size/XS, area/libsinsp

#1918 new(ci): added an initial perf-related CI.
  .github/workflows/create-comment.yml
  .github/workflows/perf.yml
Labels: kind/feature, release-note, dco-signoff: yes, lgtm, approved, size/L, area/CI

#1923 fix(sinsp): invalid threads shoudln't be in a pid namespace
  userspace/libsinsp/threadinfo.h
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/libsinsp

#1893 cleanup(libsinsp): introduce param->as<std::string>(), add error for unsupported types
  userspace/libsinsp/event.cpp
  userspace/libsinsp/event.h
  userspace/libsinsp/parsers.cpp
  userspace/libsinsp/sinsp_filtercheck_event.cpp
  userspace/libsinsp/sinsp_filtercheck_fd.cpp
  userspace/libsinsp/test/events_param.ut.cpp
Labels: release-note, dco-signoff: yes, lgtm, approved, size/M, kind/cleanup, area/libsinsp

#1931 fix(libpman): avoid truncated verifier logs
  userspace/libpman/src/configuration.c
  userspace/libpman/src/lifecycle.c
  userspace/libpman/src/state.h
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/M, area/libpman

#1886 fix: class definitions with duplicate names
  userspace/libsinsp/test/plugins/metrics.cpp
  userspace/libsinsp/test/plugins/plugin_extract.cpp
  userspace/libsinsp/test/plugins/plugin_source.cpp
  userspace/libsinsp/test/plugins/syscall_async.cpp
  userspace/libsinsp/test/plugins/syscall_extract.cpp
  userspace/libsinsp/test/plugins/syscall_parse.cpp
  userspace/libsinsp/test/plugins/syscall_source.cpp
  userspace/libsinsp/test/plugins/syscall_subtables.cpp
  userspace/libsinsp/test/plugins/syscall_subtables_array.cpp
  userspace/libsinsp/test/plugins/syscall_tables.cpp
Labels: dco-signoff: yes, release-note-none, lgtm, approved, kind/cleanup, area/build, size/XL

#1933 chore(ci): small fix in output names.
  .github/actions/composite-perf/action.yml
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/CI

#1934 fix(ci): fixed heaptrack data path (zst extension).
  .github/actions/composite-perf/action.yml
  .github/workflows/perf.yml
Labels: kind/bug, dco-signoff: yes, release-note-none, lgtm, approved, size/XS, area/CI

#1899 update(cmake): Build zlib using CMake on Windows
  cmake/modules/zlib.cmake
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved, kind/cleanup, area/build

#1940 update(cmake): Make sure we link zlib with the correct Windows CRT
  cmake/modules/zlib.cmake
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS, kind/cleanup, area/build, area/CI
